# Site settings
title: Erika Mumford, Poet
email: sunraydust@gmail.com
baseurl: ""
url: "https://erikamumford.net"

# Build settings
markdown: kramdown
source: src
collections:
  doorintheforest:
    output: true
    permalink: /:collection/:name
  karmabazaar:
    output: true
    permalink: /:collection/:name
  willowwater:
    output: true
    permalink: /:collection/:name
  wordsformyself:
    output: true
    permalink: /:collection/:name
