# Site settings
title: Erika Mumford, Poet
email: sunraydust@gmail.com
baseurl: ""
url: "https://erikamumford.net"

# Build settings
markdown: kramdown
source: src
collections:
  output: true
  permalink: /:collection/:name
