# config.yml

backend:
  name: git-gateway
  branch: master
media_folder: 'media'
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
  - name: 'doorintheforest'
    label: 'Door in the Forest'
    folder: 'doorintheforest/'
    fields:
      - { name: Title }
